import type { Company } from "@/types/company";
import type { Contact } from "@/types/contact";
import type { Job } from "@/types/job";
import type { Lead } from "@/types/lead";
import type { Campaign } from "@/types/campaign";
import type { Employee } from "@/types/employee";

export const mockCompanies: Company[] = [
  {
    id: "co_1",
    company_name: "Acme AI",
    company_domain: "acme.ai",
    company_website: "https://acme.ai",
    company_linkedin_url: "https://linkedin.com/company/acme-ai",
    company_phone: "+44 20 7946 0958",
    employee_count: 850,
    industry: "Artificial Intelligence",
    location: "London, UK",
    leads_count: 3,
    jobs_count: 2,
    contacts_count: 2,
  },
  {
    id: "co_2",
    company_name: "Nimbus Cloud Systems",
    company_domain: "nimbuscloud.io",
    company_website: "https://nimbuscloud.io",
    company_linkedin_url: "https://linkedin.com/company/nimbus-cloud",
    company_phone: "+1 415 555 0134",
    employee_count: 4200,
    industry: "Cloud Infrastructure",
    location: "San Francisco, CA",
    leads_count: 2,
    jobs_count: 2,
    contacts_count: 2,
  },
  {
    id: "co_3",
    company_name: "Bright Ledger Analytics",
    company_domain: "brightledger.com",
    company_website: "https://brightledger.com",
    company_linkedin_url: "https://linkedin.com/company/bright-ledger",
    company_phone: undefined,
    employee_count: 25,
    industry: "Fintech",
    location: "Berlin, Germany",
    leads_count: 0,
    jobs_count: 1,
    contacts_count: 0,
  },
  {
    id: "co_4",
    company_name: "Vertex Robotics Group",
    company_domain: "vertexrobotics.com",
    company_website: "https://vertexrobotics.com",
    company_linkedin_url: "https://linkedin.com/company/vertex-robotics",
    company_phone: "+1 617 555 0192",
    employee_count: 15400,
    industry: "Robotics & Automation",
    location: "Boston, MA",
    leads_count: 1,
    jobs_count: 1,
    contacts_count: 1,
  },
  {
    id: "co_5",
    company_name: "Solace HealthTech",
    company_domain: "solacehealth.com",
    company_website: "https://solacehealth.com",
    company_linkedin_url: "https://linkedin.com/company/solace-healthtech",
    company_phone: "+44 161 555 0110",
    employee_count: 620,
    industry: "Digital Health",
    location: "Manchester, UK",
    leads_count: 4,
    jobs_count: 4,
    contacts_count: 5,
  },
];

export const mockContacts: Contact[] = [
  {
    id: "ct_1",
    name: "Daniel Reyes",
    job_title: "Head of Machine Learning",
    email: "daniel.reyes@acme.ai",
    phone: "+44 7700 900123",
    linkedin_url: "https://linkedin.com/in/danielreyes",
    company_name: "Acme AI",
    company_domain: "acme.ai",
    contact_type: "job_poster",
    apollo_person_id: "apollo_10021",
    source: "Apollo",
    enrichment_status: "enriched",
    created_at: "2026-08-10T09:12:00Z",
    updated_at: "2026-08-10T09:12:00Z",
  },
  {
    id: "ct_2",
    name: "Jane Smith",
    job_title: "Technical Recruiter",
    email: "jane.smith@acme.ai",
    phone: undefined,
    linkedin_url: "https://linkedin.com/in/janesmithrecruiter",
    company_name: "Acme AI",
    company_domain: "acme.ai",
    contact_type: "hr_recruiter",
    apollo_person_id: "apollo_10022",
    source: "Apollo",
    enrichment_status: "enriched",
    created_at: "2026-08-11T14:02:00Z",
    updated_at: "2026-08-11T14:02:00Z",
  },
  {
    id: "ct_3",
    name: "Priya Chandrasekaran",
    job_title: "Senior Platform Engineer Manager",
    email: "priya.c@nimbuscloud.io",
    phone: "+1 415 555 0187",
    linkedin_url: "https://linkedin.com/in/priyachandra",
    company_name: "Nimbus Cloud Systems",
    company_domain: "nimbuscloud.io",
    contact_type: "job_poster",
    apollo_person_id: "apollo_10045",
    source: "Apollo",
    enrichment_status: "enriched",
    created_at: "2026-08-09T11:30:00Z",
    updated_at: "2026-08-09T11:30:00Z",
  },
  {
    id: "ct_4",
    name: "Marcus Webb",
    job_title: "Talent Acquisition Partner",
    email: undefined,
    phone: "+1 415 555 0199",
    linkedin_url: "https://linkedin.com/in/marcuswebb",
    company_name: "Nimbus Cloud Systems",
    company_domain: "nimbuscloud.io",
    contact_type: "hr_recruiter",
    apollo_person_id: "apollo_10046",
    source: "Apollo",
    enrichment_status: "enriched",
    created_at: "2026-08-08T08:45:00Z",
    updated_at: "2026-08-08T08:45:00Z",
  },
  {
    id: "ct_5",
    name: "Helen Cho",
    job_title: "Recruiting Coordinator",
    email: "helen.cho@vertexrobotics.com",
    phone: "+1 617 555 0155",
    linkedin_url: "https://linkedin.com/in/helencho",
    company_name: "Vertex Robotics Group",
    company_domain: "vertexrobotics.com",
    contact_type: "hr_recruiter",
    apollo_person_id: "apollo_10067",
    source: "Apollo",
    enrichment_status: "enriched",
    created_at: "2026-08-07T16:20:00Z",
    updated_at: "2026-08-07T16:20:00Z",
  },
  {
    id: "ct_6",
    name: "Oliver Bennett",
    job_title: "VP of Engineering",
    email: "oliver.bennett@solacehealth.com",
    phone: "+44 161 555 0177",
    linkedin_url: "https://linkedin.com/in/oliverbennett",
    company_name: "Solace HealthTech",
    company_domain: "solacehealth.com",
    contact_type: "job_poster",
    apollo_person_id: "apollo_10089",
    source: "Apollo",
    enrichment_status: "enriched",
    created_at: "2026-08-12T10:05:00Z",
    updated_at: "2026-08-12T10:05:00Z",
  },
  {
    id: "ct_7",
    name: "Sofia Marchetti",
    job_title: "People Operations Lead",
    email: "sofia.m@solacehealth.com",
    phone: "+44 161 555 0188",
    linkedin_url: "https://linkedin.com/in/sofiamarchetti",
    company_name: "Solace HealthTech",
    company_domain: "solacehealth.com",
    contact_type: "hr_recruiter",
    apollo_person_id: "apollo_10090",
    source: "Apollo",
    enrichment_status: "enriched",
    created_at: "2026-08-06T13:40:00Z",
    updated_at: "2026-08-06T13:40:00Z",
  },
  {
    id: "ct_8",
    name: "Ryan Osei",
    job_title: "Engineering Manager",
    email: undefined,
    phone: undefined,
    linkedin_url: "https://linkedin.com/in/ryanosei",
    company_name: "Solace HealthTech",
    company_domain: "solacehealth.com",
    contact_type: "job_poster",
    apollo_person_id: "apollo_10091",
    source: "Apollo",
    enrichment_status: "enriched",
    created_at: "2026-08-05T09:15:00Z",
    updated_at: "2026-08-05T09:15:00Z",
  },
  {
    id: "ct_9",
    name: "Emily Zhao",
    job_title: "Senior Technical Recruiter",
    email: "emily.zhao@solacehealth.com",
    phone: "+44 161 555 0201",
    linkedin_url: "https://linkedin.com/in/emilyzhao",
    company_name: "Solace HealthTech",
    company_domain: "solacehealth.com",
    contact_type: "hr_recruiter",
    apollo_person_id: "apollo_10092",
    source: "Apollo",
    enrichment_status: "enriched",
    created_at: "2026-08-04T15:55:00Z",
    updated_at: "2026-08-04T15:55:00Z",
  },
  {
    id: "ct_10",
    name: "Thomas Nguyen",
    job_title: "Founding Engineer",
    email: "thomas@brightledger.com",
    phone: "+49 30 555 0142",
    linkedin_url: "https://linkedin.com/in/thomasnguyen",
    company_name: "Bright Ledger Analytics",
    company_domain: "brightledger.com",
    contact_type: "job_poster",
    apollo_person_id: "apollo_10099",
    source: "Apollo",
    enrichment_status: "enriched",
    created_at: "2026-08-03T12:10:00Z",
    updated_at: "2026-08-03T12:10:00Z",
  },
];

export const mockJobs: Job[] = [
  {
    id: "job_1",
    campaign_id: "camp_1",
    job_posting_id: "3812093812",
    job_title: "AI/ML Engineer",
    company_name: "Acme AI",
    company_id: "co_1",
    company_url: "https://linkedin.com/company/acme-ai",
    job_location: "London, UK",
    job_summary:
      "Acme AI is looking for an AI/ML Engineer to build and ship production ML systems for our core platform.",
    job_description:
      "We are looking for an experienced AI/ML Engineer to join our core platform team. You will design, train, and deploy machine learning models that power our production recommendation and forecasting systems.\n\nResponsibilities:\n- Design and implement scalable ML pipelines\n- Collaborate with product and data teams to define model requirements\n- Own model performance monitoring in production\n\nRequirements:\n- 4+ years of experience in ML engineering\n- Strong Python skills, experience with PyTorch or TensorFlow\n- Experience with cloud ML infrastructure (AWS/GCP)",
    job_seniority_level: "Mid-Senior level",
    job_function: "Engineering",
    job_employment_type: "Full-time",
    job_industries: "Artificial Intelligence",
    job_remote_type: "On-site",
    job_posted_time: "9 hours ago",
    job_posted_date: "2026-08-16T05:00:00Z",
    job_num_applicants: 23,
    application_availability: true,
    linkedin_url: "https://linkedin.com/jobs/view/3812093812",
    company_employee_count: 850,
    qualified: true,
    qualification_reason:
      "Applicant count is 23 and company employee count is 850, which satisfies all configured filters.",
    qualification_checks: [
      { label: "Applicant count", value: "23", expected: "maximum 99", passed: true },
      { label: "Company size", value: "850", expected: "50–10,000", passed: true },
      { label: "Job type", value: "Full-time", expected: "Full-time", passed: true },
      { label: "Remote", value: "On-site", expected: "On-site", passed: true },
    ],
    contact: mockContacts[0],
    company: mockCompanies[0],
  },
  {
    id: "job_2",
    campaign_id: "camp_1",
    job_posting_id: "3812093813",
    job_title: "Senior Platform Engineer",
    company_name: "Nimbus Cloud Systems",
    company_id: "co_2",
    company_url: "https://linkedin.com/company/nimbus-cloud",
    job_location: "San Francisco, CA",
    job_summary:
      "Nimbus Cloud Systems is hiring a Senior Platform Engineer for our infrastructure team.",
    job_description:
      "Join our platform team building the next generation of cloud infrastructure tooling used by thousands of engineering teams.\n\nResponsibilities:\n- Build and maintain internal developer platform services\n- Improve reliability and scalability of core infrastructure\n- Mentor junior engineers\n\nRequirements:\n- 6+ years in platform/infrastructure engineering\n- Deep knowledge of Kubernetes and distributed systems",
    job_seniority_level: "Mid-Senior level",
    job_function: "Engineering",
    job_employment_type: "Full-time",
    job_industries: "Cloud Infrastructure",
    job_remote_type: "Hybrid",
    job_posted_time: "1 day ago",
    job_posted_date: "2026-08-15T09:00:00Z",
    job_num_applicants: 76,
    application_availability: true,
    linkedin_url: "https://linkedin.com/jobs/view/3812093813",
    company_employee_count: 4200,
    qualified: true,
    qualification_reason:
      "Applicant count is 76 and company employee count is 4,200, which satisfies all configured filters.",
    qualification_checks: [
      { label: "Applicant count", value: "76", expected: "maximum 99", passed: true },
      { label: "Company size", value: "4,200", expected: "50–10,000", passed: true },
      { label: "Job type", value: "Full-time", expected: "Full-time", passed: true },
      { label: "Remote", value: "Hybrid", expected: "On-site", passed: false },
    ],
    contact: mockContacts[2],
    company: mockCompanies[1],
  },
  {
    id: "job_3",
    campaign_id: "camp_1",
    job_posting_id: "3812093814",
    job_title: "Staff Software Engineer",
    company_name: "Nimbus Cloud Systems",
    company_id: "co_2",
    company_url: "https://linkedin.com/company/nimbus-cloud",
    job_location: "Remote - US",
    job_summary: "Staff-level engineer to lead our data platform initiatives.",
    job_description:
      "We're hiring a Staff Software Engineer to lead architecture decisions across our data platform.\n\nRequirements:\n- 8+ years experience\n- Track record of leading large technical initiatives",
    job_seniority_level: "Director",
    job_function: "Engineering",
    job_employment_type: "Full-time",
    job_industries: "Cloud Infrastructure",
    job_remote_type: "Remote",
    job_posted_time: "2 days ago",
    job_posted_date: "2026-08-14T09:00:00Z",
    job_num_applicants: 134,
    application_availability: true,
    linkedin_url: "https://linkedin.com/jobs/view/3812093814",
    company_employee_count: 4200,
    qualified: false,
    rejection_reasons: ["Applicant count is above 99."],
    qualification_reason: "Applicant count is above 99.",
    qualification_checks: [
      { label: "Applicant count", value: "100+", expected: "maximum 99", passed: false },
      { label: "Company size", value: "4,200", expected: "50–10,000", passed: true },
      { label: "Job type", value: "Full-time", expected: "Full-time", passed: true },
      { label: "Remote", value: "Remote", expected: "On-site", passed: false },
    ],
    contact: mockContacts[3],
    company: mockCompanies[1],
  },
  {
    id: "job_4",
    campaign_id: "camp_1",
    job_posting_id: "3812093815",
    job_title: "Backend Engineer",
    company_name: "Bright Ledger Analytics",
    company_id: "co_3",
    company_url: "https://linkedin.com/company/bright-ledger",
    job_location: "Berlin, Germany",
    job_summary: "Early-stage fintech looking for a backend engineer.",
    job_description:
      "Bright Ledger is a small fintech startup building analytics tools for accountants.\n\nRequirements:\n- Experience with Node.js or Python\n- Comfortable in a small team environment",
    job_seniority_level: "Mid-Senior level",
    job_function: "Engineering",
    job_employment_type: "Full-time",
    job_industries: "Fintech",
    job_remote_type: "On-site",
    job_posted_time: "3 days ago",
    job_posted_date: "2026-08-13T09:00:00Z",
    job_num_applicants: 12,
    application_availability: true,
    linkedin_url: "https://linkedin.com/jobs/view/3812093815",
    company_employee_count: 25,
    qualified: false,
    rejection_reasons: ["Company has 25 employees. Minimum is 50."],
    qualification_reason: "Company has 25 employees. Minimum is 50.",
    qualification_checks: [
      { label: "Applicant count", value: "12", expected: "maximum 99", passed: true },
      { label: "Company size", value: "25", expected: "50–10,000", passed: false },
      { label: "Job type", value: "Full-time", expected: "Full-time", passed: true },
      { label: "Remote", value: "On-site", expected: "On-site", passed: true },
    ],
    contact: mockContacts[9],
    company: mockCompanies[2],
  },
  {
    id: "job_5",
    campaign_id: "camp_1",
    job_posting_id: "3812093816",
    job_title: "Principal Robotics Engineer",
    company_name: "Vertex Robotics Group",
    company_id: "co_4",
    company_url: "https://linkedin.com/company/vertex-robotics",
    job_location: "Boston, MA",
    job_summary: "Large robotics company hiring a principal engineer.",
    job_description:
      "Vertex Robotics is looking for a Principal Robotics Engineer to lead our autonomy stack.\n\nRequirements:\n- 10+ years of robotics experience\n- PhD preferred",
    job_seniority_level: "Director",
    job_function: "Engineering",
    job_employment_type: "Full-time",
    job_industries: "Robotics & Automation",
    job_remote_type: "On-site",
    job_posted_time: "4 days ago",
    job_posted_date: "2026-08-12T09:00:00Z",
    job_num_applicants: 45,
    application_availability: true,
    linkedin_url: "https://linkedin.com/jobs/view/3812093816",
    company_employee_count: 15400,
    qualified: false,
    rejection_reasons: ["Company has 15,400 employees. Maximum is 10,000."],
    qualification_reason: "Company has 15,400 employees. Maximum is 10,000.",
    qualification_checks: [
      { label: "Applicant count", value: "45", expected: "maximum 99", passed: true },
      { label: "Company size", value: "15,400", expected: "50–10,000", passed: false },
      { label: "Job type", value: "Full-time", expected: "Full-time", passed: true },
      { label: "Remote", value: "On-site", expected: "On-site", passed: true },
    ],
    contact: mockContacts[4],
    company: mockCompanies[3],
  },
  {
    id: "job_6",
    campaign_id: "camp_1",
    job_posting_id: "3812093817",
    job_title: "Full Stack Engineer",
    company_name: "Solace HealthTech",
    company_id: "co_5",
    company_url: "https://linkedin.com/company/solace-healthtech",
    job_location: "Manchester, UK",
    job_summary: "Digital health company hiring a full stack engineer.",
    job_description:
      "Solace HealthTech builds remote patient monitoring software used by NHS trusts across the UK.\n\nRequirements:\n- Experience with React and Python\n- Interest in healthcare technology",
    job_seniority_level: "Mid-Senior level",
    job_function: "Engineering",
    job_employment_type: "Full-time",
    job_industries: "Digital Health",
    job_remote_type: "On-site",
    job_posted_time: "12 hours ago",
    job_posted_date: "2026-08-16T02:00:00Z",
    job_num_applicants: 8,
    application_availability: true,
    linkedin_url: "https://linkedin.com/jobs/view/3812093817",
    company_employee_count: 620,
    qualified: true,
    qualification_reason:
      "Applicant count is 8 and company employee count is 620, which satisfies all configured filters.",
    qualification_checks: [
      { label: "Applicant count", value: "8", expected: "maximum 99", passed: true },
      { label: "Company size", value: "620", expected: "50–10,000", passed: true },
      { label: "Job type", value: "Full-time", expected: "Full-time", passed: true },
      { label: "Remote", value: "On-site", expected: "On-site", passed: true },
    ],
    contact: mockContacts[5],
    company: mockCompanies[4],
  },
  {
    id: "job_7",
    campaign_id: "camp_1",
    job_posting_id: "3812093818",
    job_title: "DevOps Engineer",
    company_name: "Solace HealthTech",
    company_id: "co_5",
    company_url: "https://linkedin.com/company/solace-healthtech",
    job_location: "Manchester, UK",
    job_summary: "DevOps engineer needed for growing health tech team.",
    job_description:
      "We're hiring a DevOps Engineer to own our CI/CD pipelines and cloud infrastructure.\n\nRequirements:\n- Experience with Terraform and AWS\n- Strong scripting skills",
    job_seniority_level: "Associate",
    job_function: "Engineering",
    job_employment_type: "Full-time",
    job_industries: "Digital Health",
    job_remote_type: "Hybrid",
    job_posted_time: "1 day ago",
    job_posted_date: "2026-08-15T08:00:00Z",
    job_num_applicants: 31,
    application_availability: true,
    linkedin_url: "https://linkedin.com/jobs/view/3812093818",
    company_employee_count: 620,
    qualified: true,
    qualification_reason:
      "Applicant count is 31 and company employee count is 620, which satisfies all configured filters.",
    qualification_checks: [
      { label: "Applicant count", value: "31", expected: "maximum 99", passed: true },
      { label: "Company size", value: "620", expected: "50–10,000", passed: true },
      { label: "Job type", value: "Full-time", expected: "Full-time", passed: true },
      { label: "Remote", value: "Hybrid", expected: "On-site", passed: false },
    ],
    contact: undefined,
    company: mockCompanies[4],
  },
  {
    id: "job_8",
    campaign_id: "camp_1",
    job_posting_id: "3812093819",
    job_title: "Product Designer",
    company_name: "Solace HealthTech",
    company_id: "co_5",
    company_url: "https://linkedin.com/company/solace-healthtech",
    job_location: "Manchester, UK",
    job_summary: "Product designer to shape our patient-facing experiences.",
    job_description:
      "Looking for a Product Designer with experience in healthcare or regulated industries.\n\nRequirements:\n- Portfolio demonstrating end-to-end product design\n- Experience with design systems",
    job_seniority_level: "Associate",
    job_function: "Design",
    job_employment_type: "Full-time",
    job_industries: "Digital Health",
    job_remote_type: "On-site",
    job_posted_time: "2 days ago",
    job_posted_date: "2026-08-14T08:00:00Z",
    job_num_applicants: 19,
    application_availability: true,
    linkedin_url: "https://linkedin.com/jobs/view/3812093819",
    company_employee_count: 620,
    qualified: true,
    qualification_reason:
      "Applicant count is 19 and company employee count is 620, which satisfies all configured filters.",
    qualification_checks: [
      { label: "Applicant count", value: "19", expected: "maximum 99", passed: true },
      { label: "Company size", value: "620", expected: "50–10,000", passed: true },
      { label: "Job type", value: "Full-time", expected: "Full-time", passed: true },
      { label: "Remote", value: "On-site", expected: "On-site", passed: true },
    ],
    contact: mockContacts[7],
    company: mockCompanies[4],
  },
  {
    id: "job_9",
    campaign_id: "camp_1",
    job_posting_id: "3812093820",
    job_title: "Data Engineer",
    company_name: "Solace HealthTech",
    company_id: "co_5",
    company_url: "https://linkedin.com/company/solace-healthtech",
    job_location: "Manchester, UK",
    job_summary: "Data engineer to build our clinical data pipelines.",
    job_description:
      "Build and maintain data pipelines that power our clinical analytics products.\n\nRequirements:\n- Experience with dbt, Airflow, or similar\n- SQL proficiency",
    job_seniority_level: "Mid-Senior level",
    job_function: "Engineering",
    job_employment_type: "Contract",
    job_industries: "Digital Health",
    job_remote_type: "Remote",
    job_posted_time: "5 hours ago",
    job_posted_date: "2026-08-16T06:00:00Z",
    job_num_applicants: 4,
    application_availability: true,
    linkedin_url: "https://linkedin.com/jobs/view/3812093820",
    company_employee_count: 620,
    qualified: false,
    rejection_reasons: ["Job type is Contract. Configured filter requires Full-time."],
    qualification_reason: "Job type is Contract. Configured filter requires Full-time.",
    qualification_checks: [
      { label: "Applicant count", value: "4", expected: "maximum 99", passed: true },
      { label: "Company size", value: "620", expected: "50–10,000", passed: true },
      { label: "Job type", value: "Contract", expected: "Full-time", passed: false },
      { label: "Remote", value: "Remote", expected: "On-site", passed: false },
    ],
    contact: mockContacts[8],
    company: mockCompanies[4],
  },
  {
    id: "job_10",
    campaign_id: "camp_1",
    job_posting_id: "3812093821",
    job_title: "Machine Learning Researcher",
    company_name: "Acme AI",
    company_id: "co_1",
    company_url: "https://linkedin.com/company/acme-ai",
    job_location: "London, UK",
    job_summary: "Research-focused ML role at Acme AI.",
    job_description:
      "Join our research team pushing the boundary of applied ML for enterprise use cases.\n\nRequirements:\n- PhD or equivalent research experience\n- Publications in top-tier ML venues preferred",
    job_seniority_level: "Mid-Senior level",
    job_function: "Research",
    job_employment_type: "Full-time",
    job_industries: "Artificial Intelligence",
    job_remote_type: "On-site",
    job_posted_time: "6 days ago",
    job_posted_date: "2026-08-10T09:00:00Z",
    job_num_applicants: 112,
    application_availability: true,
    linkedin_url: "https://linkedin.com/jobs/view/3812093821",
    company_employee_count: 850,
    qualified: false,
    rejection_reasons: ["Applicant count is above 99."],
    qualification_reason: "Applicant count is above 99.",
    qualification_checks: [
      { label: "Applicant count", value: "100+", expected: "maximum 99", passed: false },
      { label: "Company size", value: "850", expected: "50–10,000", passed: true },
      { label: "Job type", value: "Full-time", expected: "Full-time", passed: true },
      { label: "Remote", value: "On-site", expected: "On-site", passed: true },
    ],
    contact: undefined,
    company: mockCompanies[0],
  },
];

export const mockLeads: Lead[] = [
  {
    id: "lead_1",
    contact: mockContacts[1],
    company: mockCompanies[0],
    job: mockJobs[0],
    lead_type: "hr_recruiter",
    status: "new",
    source: "Apollo",
    created_at: "2026-08-16T05:30:00Z",
    updated_at: "2026-08-16T05:30:00Z",
    notes: "Reached out via LinkedIn about the AI/ML Engineer role.",
  },
  {
    id: "lead_2",
    contact: mockContacts[0],
    company: mockCompanies[0],
    job: mockJobs[0],
    lead_type: "job_poster",
    status: "contacted",
    source: "Apollo",
    created_at: "2026-08-15T09:00:00Z",
    updated_at: "2026-08-16T08:00:00Z",
    notes: "Sent intro email, waiting on reply.",
  },
  {
    id: "lead_3",
    contact: mockContacts[2],
    company: mockCompanies[1],
    job: mockJobs[1],
    lead_type: "job_poster",
    status: "qualified",
    source: "Apollo",
    created_at: "2026-08-14T11:00:00Z",
    updated_at: "2026-08-15T13:00:00Z",
  },
  {
    id: "lead_4",
    contact: mockContacts[3],
    company: mockCompanies[1],
    job: mockJobs[2],
    lead_type: "hr_recruiter",
    status: "new",
    source: "Apollo",
    created_at: "2026-08-14T12:00:00Z",
    updated_at: "2026-08-14T12:00:00Z",
  },
  {
    id: "lead_5",
    contact: mockContacts[9],
    company: mockCompanies[2],
    job: mockJobs[3],
    lead_type: "job_poster",
    status: "rejected",
    source: "Apollo",
    created_at: "2026-08-13T09:30:00Z",
    updated_at: "2026-08-13T17:00:00Z",
    notes: "Company too small for our ICP.",
  },
  {
    id: "lead_6",
    contact: mockContacts[4],
    company: mockCompanies[3],
    job: mockJobs[4],
    lead_type: "hr_recruiter",
    status: "converted",
    source: "Apollo",
    created_at: "2026-08-08T09:00:00Z",
    updated_at: "2026-08-12T10:00:00Z",
    notes: "Closed as a customer opportunity.",
  },
  {
    id: "lead_7",
    contact: mockContacts[5],
    company: mockCompanies[4],
    job: mockJobs[5],
    lead_type: "job_poster",
    status: "new",
    source: "Apollo",
    created_at: "2026-08-16T02:30:00Z",
    updated_at: "2026-08-16T02:30:00Z",
  },
  {
    id: "lead_8",
    contact: mockContacts[6],
    company: mockCompanies[4],
    job: mockJobs[6],
    lead_type: "hr_recruiter",
    status: "contacted",
    source: "Apollo",
    created_at: "2026-08-15T10:00:00Z",
    updated_at: "2026-08-16T09:00:00Z",
  },
  {
    id: "lead_9",
    contact: mockContacts[7],
    company: mockCompanies[4],
    job: mockJobs[7],
    lead_type: "job_poster",
    status: "new",
    source: "Apollo",
    created_at: "2026-08-14T08:15:00Z",
    updated_at: "2026-08-14T08:15:00Z",
    notes: "No email or phone on file yet.",
  },
  {
    id: "lead_10",
    contact: mockContacts[8],
    company: mockCompanies[4],
    job: mockJobs[8],
    lead_type: "hr_recruiter",
    status: "qualified",
    source: "Manual",
    created_at: "2026-08-12T15:00:00Z",
    updated_at: "2026-08-13T09:00:00Z",
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: "camp_1",
    name: "Campaign_20260816_ai-ml-engineer",
    role_name: "AI/ML Engineer",
    search_filters: {
      keyword: "AI/ML Engineer",
      location: "London",
      country: "GB",
      time_range: "Past 24 hours",
      job_type: "Full-time",
      experience_level: "Mid-Senior level",
      remote: "On-site",
      company: "",
      location_radius: "25",
      max_applicants: 99,
      min_company_size: 50,
      max_company_size: 10000,
    },
    stage: "jobs_review",
    status: "active",
    created_at: "2026-08-16T05:00:00Z",
  },
];

export const mockEmployees: Employee[] = [
  {
    id: "emp_1",
    name: "Asha Rao",
    role_title: "Senior Java Developer",
    skills: ["Java", "Spring", "AWS"],
    experience_years: 6,
    availability: "available",
    email: "asha@example.com",
    summary: "Backend specialist with deep experience shipping high-throughput Java services on AWS.",
  },
  {
    id: "emp_2",
    name: "Miguel Santos",
    role_title: "React Frontend Engineer",
    skills: ["React", "TypeScript", "Next.js"],
    experience_years: 4,
    availability: "available",
    email: "miguel@example.com",
    summary: "Frontend engineer focused on design systems and performance-critical React apps.",
  },
  {
    id: "emp_3",
    name: "Priya Nair",
    role_title: "DevOps Engineer",
    skills: ["Kubernetes", "AWS", "Terraform"],
    experience_years: 5,
    availability: "on-bench",
    email: "priya@example.com",
    summary: "Infrastructure engineer who has led migrations to Kubernetes at two prior companies.",
  },
  {
    id: "emp_4",
    name: "Daniel Kim",
    role_title: "Data Engineer",
    skills: ["Python", "Spark", "Airflow"],
    experience_years: 3,
    availability: "available",
    email: "daniel@example.com",
    summary: "Builds and maintains large-scale batch and streaming data pipelines.",
  },
  {
    id: "emp_5",
    name: "Sara Ahmed",
    role_title: "QA Automation Engineer",
    skills: ["Selenium", "Python", "CI/CD"],
    experience_years: 4,
    availability: "available",
    email: "sara@example.com",
    summary: "Owns test automation strategy and CI/CD pipeline health for product teams.",
  },
];
